# Site settings
title: committed coder
description: "coding is a journey, the destination keeps on changing"
baseurl: ""
url: "http://www.committedcoder.com"
paginate: 10

# Build settings
markdown: kramdown
permalink: /:title.html

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

gems:
  - jekyll-sitemap