# Site settings
title: committed coder
description: "coding is a journey, the destination keeps on changing"
baseurl: ""
url: "http://www.committedcoder.com"
enable_analytics: true
enable_discus: true

# Build settings
markdown: kramdown
permalink: /:title.html
excerpt_separator: "<!--more-->"
exclude: ['Gemfile', 'Gemfile.lock', 'package.json', 'gulpfile.js', 'README.md']
paginate: 10

